### ISSUE TITLE
Under Therapeutic Target:  The alphabets for Upper and lower case letters need to be merged.

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#100]
We realize that visually this may not look as nice, however it is more important that there be a single alphabetic list.

**Comment by gbohara** [comment]
Cindy, can you elaborate a litte on this? Is in on data entry or detail page?

**Comment by sheffieldcl** [comment]
Ganga this occurs on the Search page in the Therapeutic Target field.
