### ISSUE TITLE
Issue with certain PMID / Related citations

### ISSUE THREAD

**Issue by svpatel1** [NIHL/AlzPED#84]
Issue with certain PMIDs - when associated "related citation titles" were longer than 255 chars, it would error out.  Item now fixed and moved to prod.

**Comment by sheffieldcl** [comment]
There was some sort of caching problem with the way PubMed cached "Related Searches" which was causing an error message, "Temporarily Unavailable
The website that you're trying to reach is having technical difficulties and is currently unavailable.
We are aware of the issue and are working hard to fix it. Thank you for your patience."
