### ISSUE TITLE
Add additional Tool Tips to Search Screen

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#86]

**Comment by sheffieldcl** [comment]
From Larry: Under the Search AlzPED tab please place the  appropriate tool tip for the following

PI Name
Therapy Type
Therapeutic Target 
Therapeutic Agent 
Model Name

**Comment by svpatel1** [comment]
we will take care of it

**Comment by sheffieldcl** [comment]
Ah, My bad, I left that field off this comments list.  Please add the Tool Tip to Model Type

**Comment by svpatel1** [comment]
All internal links will open in same tab, all external links (with urls that do not have alzped in them) , will open in new tabs. (except for home page)
