### ISSUE TITLE
Add ability to add greek characters to the Title field.

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#87]

**Comment by svpatel1** [comment]
We'd like to learn more about how data is entered, this will help us with finding the optimal solution

**Comment by sheffieldcl** [comment]
I can set up a WebEx, and include Katrina as well.  Is there are preferred time to do that?

**Comment by sheffieldcl** [comment]
Sanjay,  I reviewed this with Larry and Katrina and they want to go ahead with adding this feature to the Title field.  Just let me know if you have any questions.  cnd

**Comment by gbohara** [comment]
Cindy, Just for the information. This won't be full fledged text editor. It will just be simple box with greek characters in it. We will be able to add more characters later (if needed)

**Comment by sheffieldcl** [comment]
Perfect!

Sent from my iPhone

On Apr 12, 2016, at 9:03 AM, gbohara <notifications@github.com<mailto:notifications@github.com>> wrote:


Cindy, Just for the information. This won't be full fledged text editor. It will just be simple box with greek characters in it. We will be able to add more characters later (if needed)

**Comment by gbohara** [comment]
Cindy, this has been completed and moved to Staging.(http://stg.alzped.nia.nih.gov)
Please review and let us know if it can be moved to production.
