### ISSUE TITLE
Add Conflict of Interest Statement as a Y/N box on the Experimental Design page

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#89]

**Comment by svpatel1** [comment]
Just to confirm - you would like to see an additional check box for "conflict of interest"  under Is the following information reported in the study?  , last check box?

**Comment by sheffieldcl** [comment]
Thank is correct!

**Comment by sheffieldcl** [comment]
Hi Sanjay,

I just spoke with Katerina and she is busy entering articles today, so she will not be able to join us.  I believe I have a good understanding of the requirement, and she concurs with that, so let’s go ahead and have that conversation today.  I don’t want to hold up the feature, as I believe it will help her with data entry.

Best regards,

Cindy

**Comment by gbohara** [comment]
This has been completed and moved to staging. The download file and details page has been taken care of.

**Comment by sheffieldcl** [comment]
Thank you Ganga!

**Comment by gbohara** [comment]
There is tooltip for all the other options.  Can you provide with the tooltip for "Conflict of Interest" option?

**Comment by sheffieldcl** [comment]
Yes, I can send that in the morning.  Thank you for noting that.
