### ISSUE TITLE
Add "Omics" as a new Outcome Measure

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#90]

**Comment by sheffieldcl** [comment]
The selection options for this drop down should be as follows: Metabolomics, Proteomics, Transcriptomics

**Comment by gbohara** [comment]
In the past, we re-ordered the list under Outcome Measure. Is there any priority for this new option? Where should it be placed?

**Comment by sheffieldcl** [comment]
Hi Ganga,

Excellent question, and good catch.  It should go at the end of the list where you have placed it.
