### ISSUE TITLE
Sort on PI Name needs to occur on the last name, not the first name

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#95]

**Comment by gbohara** [comment]
What should the display be like. I think the display should also be last name + middle initial + first name

**Comment by gbohara** [comment]
Correct me if I am wrong. 
The display on the results page
https://alzped.nia.nih.gov/alzped-search/results?content=Noble%20Wendy
and 
Detail page 
https://alzped.nia.nih.gov/minocycline-reduces
both should read "Noble Wendy" instead of  "Wendy Noble"

**Comment by sheffieldcl** [comment]
Hi Ganga,

I’m getting ready to go into a meeting.  Let me get back to you on this so we know we are thinking the same thing.

Cindy

**Comment by sheffieldcl** [comment]
Hi Ganga, That display is correct.  If there were a middle initial it could be Wendy D. Noble.   We just want to be sure the system sorts by Last Name of the PI.  Just give me a call if you have more questions.

**Comment by svpatel1** [comment]
sorts on last name now, but displays with <firstname> <middle initial> <lastname>
