### ISSUE TITLE
The Sort by APID needs to be corrected so that numbers with additional decimal points fall into the right sequence

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#96]

**Comment by sheffieldcl** [comment]
For instance 13060416 should not come before 4510715

**Comment by svpatel1** [comment]
we do not understand what "decimal pts." means - as none of the existing apid's have decimals.

**Comment by svpatel1** [comment]
now that we are sorting as a number, decimal may work now. requires testing
