### ISSUE TITLE
All links on the site should open to a new screen

### ISSUE THREAD

**Issue by sheffieldcl** [NIHL/AlzPED#98]
This includes links within an individual record, the Resources page, and any other link on the site.

**Comment by svpatel1** [comment]
Is open in a "new tab" acceptable?

**Comment by sheffieldcl** [comment]
Open is a "new tab" is acceptable.  I believe most people know how to separate screens.  Larry and I did have that conversation.

**Comment by theBrarian** [comment]
There is a lot of debate as to best practice regarding this and I tend to fall on the side of keeping links in the same tab and allowing the user to choose the behavior they prefer. By adding "target=_blank" you are taking some of the users control away. It is also problematic for accessibility as some screen readers do not tell you it is a new tab, or the newer ones only tell you after you have followed the link. I would suggest not forcing links into a new tab.

**Comment by sheffieldcl** [comment]
Hi Brian,

I appreciate the your input and you did a great job beta testing the site!  You showed me weak points that I had not consider prior.  On beta testing AlzPED within the scientific community, users have unanimously voiced that it is easier for them to compare information between tabs and back to the original citation, and to navigate back to AlzPED, as some of the other sites will not let you go directly back to AlzPED.  So we have opted to do that.

Thanks again for providing a different prospective.  I think it is helpful to have various viewpoints while trying to make these determinations.

Best regards,

Cindy

**Comment by svpatel1** [comment]
I'd like to talk about this a bit more with you Cindy if that would be ok. I think we should find a  balance as to which links make sense to see which links should open in new tabs and which are not  a good idea...  Section 508 is also an important consideration; this is the closest guidance we could find on the issue - http://guidelines.usability.gov/guidelines/67, which I think? says that every page should have a back button (ie avoid new tabs).  Another good article on the links :  http://www.digitalgov.gov/2015/02/25/avoid-weak-links-in-your-digital-chain/ . we may also want to add an icon that denotes the links as external.

**Comment by sheffieldcl** [comment]
Good point re: 508.   I think we can find that balance.  Do you want to pick a time that works for you this afternoon and just give me a call when you are ready?

**Comment by svpatel1** [comment]
Internal links (i.e. urls that have alzped.nih.gov) - will open in the current tab. External links (urls that do not have alzped.nih.gov) will open in a new tab. this applies to the entire site.

**Comment by gbohara** [comment]
This has been enabled on the live site.
